{% set name = "alphalens-reloaded" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: af2dcb4c2c01dbc1cc813fc5d6824b185145528a7f5c660dc168af488d83cbba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - matplotlib-base >=1.4.0
    - numpy >=1.9.1
    - pandas >=1.0.0
    - scipy >=0.14.0
    - seaborn >=0.6.0
    - statsmodels >=0.6.1
    - ipython >=3.2.3
    - empyrical-reloaded >=0.5.7

test:
  imports:
    - alphalens
  source_files:
    - tests
  commands:
    - pytest tests/
  requires:
    - coverage >=4.0.3
    - coveralls ==3.0.1
    - pytest >=6.2
    - pytest-xdist >=2.5.0
    - pytest-cov >=2.12
    - parameterized >=0.6.1

about:
  home: https://pypi.org/project/alphalens-reloaded/
  summary: Performance analysis of predictive (alpha) stock factors
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stefan-jansen
